# Generated by Django 4.0.3 on 2022-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_messages_chat_delete_chats_delete_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
