# Generated by Django 4.0.3 on 2022-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_customuser_about_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_specialVerified',
            field=models.BooleanField(default=False),
        ),
    ]
