# Generated by Django 4.0.3 on 2022-05-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_customuser_is_specialverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='delivery_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
