# Generated by Django 4.0.3 on 2022-05-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_bids_amount_jobs_due_date_alter_jobs_delivery_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='workingDays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
