# Generated by Django 4.0.2 on 2022-05-14 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_bids_workingdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='freelancer',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
