# Generated by Django 4.0.2 on 2022-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_bids_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='freelancer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
