# Generated by Django 4.0.2 on 2022-05-14 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_bids_freelancer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='job',
            new_name='jobId',
        ),
        migrations.RenameField(
            model_name='funds',
            old_name='job',
            new_name='jobId',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='client',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='bids',
            name='username',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
