# Generated by Django 4.0.2 on 2022-05-14 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_rename_job_bids_jobid_rename_job_funds_jobid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
