# Generated by Django 4.0.2 on 2022-05-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_bids_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
