# Generated by Django 4.0.2 on 2022-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_bids_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='jobId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
